# Generated by Django 4.2.3 on 2024-04-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ihas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('max_flight_time', models.PositiveIntegerField()),
                ('max_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('battery_capacity', models.PositiveIntegerField()),
                ('sensors', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
            options={
                'db_table': 'ihas',
            },
        ),
    ]
