# Generated by Django 4.2.3 on 2024-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        ('ihas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihas',
            name='sensors',
        ),
        migrations.AddField(
            model_name='ihas',
            name='sensors',
            field=models.ManyToManyField(to='sensors.sensors'),
        ),
    ]
