# Generated by Django 4.2.3 on 2024-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        ('ihas', '0002_remove_ihas_sensors_ihas_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihas',
            name='battery_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='max_flight_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='max_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='sensors',
            field=models.ManyToManyField(blank=True, null=True, to='sensors.sensors'),
        ),
    ]
